{% set name = "Lagranto" %}
{% set version = "0.1.5" %}
{% set sha256 = "0cb9e4405563a0c0c0ba669823a02128250b5f4f806f0beaf8b732b5cd9073fb"%}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://git.iac.ethz.ch/npiaget/Lagranto/repository/v{{version}}/archive.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [win]


requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - cartopy
    - netcdf4
    - path.py
    - matplotlib

test:
  imports:
    - lagranto
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - py.test
 
about:
  home: https://git.iac.ethz.ch/npiaget/Lagranto
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'Library to work with trajectories.'

  doc_url: https://lagranto.readthedocs.io/en/latest/
  dev_url: https://git.iac.ethz.ch/npiaget/Lagranto

extra:
  recipe-maintainers:
    - npiaget
