# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "j5ZZSIWtM2uSbZsDU5y/B1jt2tz7BGUaf/kCmBL8vODHt8793MxnJWvBO6hkN0yIEyH5xFFgezR9ArsKp3H78eN1VBYJMCKEobRp7HVWyToZz5CxmG9tDmVjrN4TPyuTD/9F+q7nmwpEM3yRVrKHbV5SlBaGvLDF2VTizv5B+eyXpthiaWi0u7QlAueOM5yFts6My9NjGjda9hKGy0FfhscnpRRbmbt+N/fHxerz2fSfA3MD+0WzlJUEf2bJJ6ch9Ykv4gxg+T9wgnUqxHNs7q+yNJvTdEt9b1RLxrPsrFnQ1AJNIzQVbsDISTrFs7XdLLASdVT1u+b1U9W4CBthEHQdHAk6up8btLpowMWHXfXCN6MNwXxrQDY9yl2PjwX8lpi4fdD6emkc/oa/zOhkeyobcoWNrWMtF9xn4w5KHPrOm+eRA+TeHCSMZbQBbpJ5Fa97/resWZSWJF61vMJUh2mJwqjwW85PCXrlrddSHLamybdN7g9pAFjO8bIS5I3VdADQ2uwMeA3h3R5Aw85hbeR8kZvdYimqXdWstZ5Qi/b/3hXmrBHcTeZeHeBGBShFSs2GMbS5qVBNcRZdifn2eTXSiJGzSuTL20Tg0289MfyKlEkT7V3+ir/5JemwwC8djuTm2bq+MHuie6VKkbKWoR+n5M9TBKJYhwIuaFLX/yM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
