travis:
  secure:
    BINSTAR_TOKEN: hFvil6IDCjhj43TQeh9iVHb5+OyzPC0LVnofjuJ+9kLGqxpjJ3JUdRv412UxhtreeCGk6HKvijm/+bjgRm1NxsFLnCbjkIPAm6gcmNXe61Gg0MhFN+eYhC08NSnBZYo417ptke9TGceJIgDR/pTpDRM+nRM+COpzZxclkUMjEN96oNkvWFZfWhsEftVv7HBOf9IdBHaD91dAZNHeqEAgQo3iefVkoGp85xGLZHcBx5uS+l6S1eSDy0KOevPw5ud9gEIHn8QFsVzhS8sjrDDOoNxFvGPXDzkjEGM+0hguzb6Hx9guh43zM9fLrFUfrqF7Gk++jEn621YpRYFcj/POd+YpQb7J5ZjtIf0mXFeBJ/oshPF7Xw/a+V3gcGWaT7ktWoR/Hqe/Khrp8GymLuQ+qvyqsN4RpsUakd9YWTerFZ6D2XXAnS2LPRni8CdKwkx5R305TivNymOGSUX0wjTLMMmPZ0pq2DHtdruq2wZZowCdEjB2nQXLuVySTB1z9ed6SBJJBTfsB6YKDMK2N4mXRjvuYDtoS6MjYmltNmh4FA/rCCixuZXyClhO70E0Ys9ZND+SGe1Sc8AD5Kj/ztBN9AnWSR0clcfyinwuEQzG8w7uTRWv89WEfW7XQhi642B/9ZRz4qrIcA19/hp9qvsesGeHU3Nif+yXoUgdbKqp4Zs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
