travis:
  secure:
    BINSTAR_TOKEN: MlGUi2IEfVUciRLcO2Br2P1BfnqEkokHqzKCo7X/uyrhz6mEB15biVI96R8XX+q8iQitzyU1EByXytXbgLdyeVoH56sR+R+qSw0l4ZqFv2tM/ZOFDPrp4H3wEZ/GpGRUsuYAA+7Tb+1RuF3qY9G1LF6BNwHOKqvWAw9sVze3EDrIpvN4oPJQ7g6RU3Vs7wFo7yVXoYDt+iSEN5ui6hOa+NmNyoLzc5f3/9NnJnM60PnVsDDyEqbZN/u2VhD1wUFn1BDO4nHsrUX0DSuwetmiGpBJn3MJ91B/CCedh6A6sQNw82pw80OiwpfXArneHPB+4+XB+S5vc/N9ZIaSbTe+Bh4buxHjzC/T+iu2hLbS3M9E19IzZPttaK2XZN+dxAzbOL73g6lpRGkkcKItyphckl0oYT8JQ9TJgOMq73Lm7ihtSNEmn66B1qwNdMl9kcwuKRzFo6zjhVGOjA66H5CVQw4FesFxXpMo6tkYjwRBbIMLovsgrGPFvL2jmOUyL8E4gkvidudTCfYx+2238+q32EI9nv2tB9IQuMerxo8L5BqZbPOfOecJVh6QOzBXVnJt8jxdnb+5BiV8aufNAshJDAse6wYrRMzscKMzV6zOzWVgfrU5opvRQL4XC5i2ZmeZ/fF3U00TzufFV/U8sZgjIXrHbElEDHY3GB6Xq332myc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
