travis:
  secure:
    BINSTAR_TOKEN: WaY0eM/ib3u2rWB/z9CddNCtjVNoRQjoSfUmhgFPY9FnDf7Okonih6kOyaxiG/bNPzggMTKOMw84TvjaNs/fXBRAEEVuIF5wCjmOhesaY+5BjAmuVueJTx1wMcxx22F97LpCpvzuYsII10ukSxLLdmFHzzxoR9xI1vYk8vrmRU40YAwE98phTI8ZVw6tAn/LJy9oYMKpGlnohD5SKn/9II3hM4DaKNtF9za5C/pCeona6C9AtZfREOSYdZO5iQTyKtz0Gs7bTMcYilfFa3J2aCXWIVqkCPjXCJI1xD+8LF3iwmvixzI7HfwkbdsYg/e7w6GeA5LbkWzcoR2r4cuHMD173PzqIvSLDomB+cp45/o6d7fy4taALFYwMXykhNnkk5xyq3lfYbUrmul02xCtNsZVYl9dMD6qAjTOBAdws38uOrIq/rpYPS8bPs5eK09cqtk903/t2GUQC07n+itNBl5ltxeuywwDm+DBrRAwtg248zxuWVnFLb+mspTymeO1BlT1/3z8JgLYHyPGYortCl9LYGN6U8o/cxaVuYpT/BDzla6ABKxybL2fU7BcqHfmTcPO5GB30hv4Nc//2p8YTadmlpX6/6gl0Z6JYsS9l8/9xcCabMpTUYuEhGj8y7+qoW47H4RKubHFaJL01b9v3AWuOTBNDw0HYDrNQjDN1oE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
