travis:
  secure:
    BINSTAR_TOKEN: MvjHRiCbxVVl5o1d1VfLVmP+z3oPsJD9Xs21M9UDTZepCcqEH9QHPzegHV3r6z6v9iDKxK/hiYhrJmEKU71Qop8B4RzD4tr7rHxBajalV6KI8G8VdunkDC82zTgUz/yzNp2zIA51CLsLQdWe7ZWxQ0vTqk51CxrITh1mSIkMUJBYQIIPX2q0AwN964q3KOCJce6W9N3D2EktUuPcMClH6L27xcuvUF0VJtsG73Mt4qDayw/N25rhO5CxvLbHjvIImwCYY0NHQuuZCJ6Trr9wB6RxlsPGbX/6IqydOaGPCoq+r8Ib+6oFsUv/C9n99dJinocBz6QiN0B2R+oIkCOTwySxmbCawBlDdt8ZURcv87yLIt2l+BTkqmeaWH2D5uqZcApnNa8emw0x7ewOUnjcVGWGYVPDx49U/3q96GjhoPC/MowhyCkjzSDCClfuNtikJNcgOp0L5SyXXGTsqVLt9MH5ANFGau8+PgZYf/qlIAmK8x9WbtncybDolh0zlA4xnbv5+CyO8b8rwzRPMJftPcJyiPOa3tdj1nvaIhy89SH7u4EEqX0it2CjsYb1/cFiyM2bkQg58ojfPkrgBI0DOdwL+qIEmmq6axyynGFqik+6U9/bCkuPFY/gC3nJA4mcmzhCjd88qoRRuirHs63G5ugEYXzp9wzr3Jstf1He6GQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
