travis:
  secure:
    BINSTAR_TOKEN: j5ZZSIWtM2uSbZsDU5y/B1jt2tz7BGUaf/kCmBL8vODHt8793MxnJWvBO6hkN0yIEyH5xFFgezR9ArsKp3H78eN1VBYJMCKEobRp7HVWyToZz5CxmG9tDmVjrN4TPyuTD/9F+q7nmwpEM3yRVrKHbV5SlBaGvLDF2VTizv5B+eyXpthiaWi0u7QlAueOM5yFts6My9NjGjda9hKGy0FfhscnpRRbmbt+N/fHxerz2fSfA3MD+0WzlJUEf2bJJ6ch9Ykv4gxg+T9wgnUqxHNs7q+yNJvTdEt9b1RLxrPsrFnQ1AJNIzQVbsDISTrFs7XdLLASdVT1u+b1U9W4CBthEHQdHAk6up8btLpowMWHXfXCN6MNwXxrQDY9yl2PjwX8lpi4fdD6emkc/oa/zOhkeyobcoWNrWMtF9xn4w5KHPrOm+eRA+TeHCSMZbQBbpJ5Fa97/resWZSWJF61vMJUh2mJwqjwW85PCXrlrddSHLamybdN7g9pAFjO8bIS5I3VdADQ2uwMeA3h3R5Aw85hbeR8kZvdYimqXdWstZ5Qi/b/3hXmrBHcTeZeHeBGBShFSs2GMbS5qVBNcRZdifn2eTXSiJGzSuTL20Tg0289MfyKlEkT7V3+ir/5JemwwC8djuTm2bq+MHuie6VKkbKWoR+n5M9TBKJYhwIuaFLX/yM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
