travis:
  secure:
    BINSTAR_TOKEN: Kwu0JnnrQ2Hkl9Js+MHJgdwOc6y3wnV3RvF8szHX0lBEQy2AzUQyQ0hnr8ZcrNidZNri5IaMvU2wnWglHBJg6wOK5QgY6deeSooDOmbWlXyfGLoQA8rJrtgmkjGCe94sBJ5EfvVSxkgibYdMZ1nfV5bnFxbr141IpgS9bBKGeImkzt+KEARl/PX2aS8eiKHup+qMOKwI4l0A48RMzK16+rBqnlbr/O9ccFdoGmqfLcDnu2mip0ULDFE6sFI/3LRODXlMp4/SHy8YVdb3YAYRaluZsKRdEqsDqhB1qNCj1zylvUocPJ+TkNGysA5xUTKpGwlrre5kkyaVB0+gLSTktVPSbWZTQqY8G34ci60wQvGlyeOm4P9D2NXrP7kbXAbr6gKao3Zhldk8VDD5UWhNIfRrBYO+fye9TvWNneB1IEnywfbTjli2MXXF2qWx/385VugLCMjztTigR96SenK/ztF2m4UtvO48NfcAVh2Vaf5NAa1FbdCHulPRM8MgbZq6RnDhs46vTsYdvRcuELClW2D3nV0PHUTDidTfzJwT2PXyKUahV3tfe/fCoVVQfntcTwn6l7CAT9E9ubSy2CDA3z34Bo9LucVdHDR79fPVTpWriG7lTRb7rXyrYqxFoitr7Evs/gDxN/Nvz2EhH9wIazWdR7HfncrjfnbMBlz7BSU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
