travis:
  secure:
    BINSTAR_TOKEN: eediFEto4ocxIf1zY0Kmzt0XJTcUci9caj/CtGhI73I2tbhdCSBz0x1euFUoEwToxuGLf3M7R3yNSBCBFX4PwyVx+6tMVDVKb0ft4Bx8hoXTkMLqlybSmjyellBS/iRdL37gPm+mMwOja8a6StLribVa5wycg8ELU/xlIWEsgzgJTMr7nQyI4Q7xx3tqJilopgETL0KxornKYj2L+yx1LJr4qNp6K4knUcLbl4IwcARsmDLtNL6dDDYDsDZkDDtsX9erBmHGIv+ctssJ7/1hBa3z/LkPwqyGUszkYW/rWs5Q82u+lv3N9/RnlwUqqmEcKlnaHJ0ckK9HijUJA6ccr6LjJzad+Q4kjamDjiZWiiOmtA6zXL9o/HasfsalUdnd+YSP79bYWL/x0Gaaw8DiZ+TXk93PyHEfcIx0x+vYdpBq+ziWgDxDUAhMcsErrfowm0g4/py3DyiZYSZS+TnyzlcbENgxDtu/AtMiCfJo70GBCukSakjNMuLLqs/ZC2ig/3VElBMGbnUgXrDY4zcyRavAWYjpIp+3BV7cAyE9pbdsgDzgZThD2hGo8JW/G/mWq71LpcEkgThxxnCHidmSZQkoQSuCqcKCorKZzOILWUS1Cq3HgR2SSIQvURQ+Mb0SuQ8KwGOfsfhD4Zy0nd+zaZiT7s7WvP6+63lHQDKWKPg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
